[project]
name = "mcp-server-deepdive-functionality"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp[cli]>=1.9.0",
    "openai>=1.79.0",
    "pyautogui>=0.9.54",
    "requests>=2.32.3",
]
